#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT_DIR/scripts/_cron_job_lib.sh"

MARKER="HIVE_CRON_ACCEPTANCE_GATE"
CRON_EXPR="${HIVE_ACCEPTANCE_GATE_CRON_EXPR:-0 * * * *}"
LOG_DIR="$ROOT_DIR/.logs"
LOG_FILE="$LOG_DIR/acceptance-gate.cron.log"
SCRIPT_PATH="$ROOT_DIR/scripts/autonomous_acceptance_gate.sh"
PROFILE="${HIVE_ACCEPTANCE_PROFILE:-balanced}"

case "$PROFILE" in
  balanced)
    DEFAULT_SKIP_CHECKLIST="true"
    DEFAULT_SKIP_TELEGRAM="false"
    DEFAULT_REPORT_KEEP="50"
    DEFAULT_REPORT_PRUNE_APPLY="false"
    DEFAULT_DIGEST_DAYS="7"
    DEFAULT_DIGEST_LIMIT="20"
    DEFAULT_ENFORCE_HISTORY="false"
    DEFAULT_HISTORY_MAX_FAIL="0"
    DEFAULT_HISTORY_MIN_PASS_RATE="1.0"
    ;;
  strict)
    DEFAULT_SKIP_CHECKLIST="true"
    DEFAULT_SKIP_TELEGRAM="false"
    DEFAULT_REPORT_KEEP="50"
    DEFAULT_REPORT_PRUNE_APPLY="false"
    DEFAULT_DIGEST_DAYS="7"
    DEFAULT_DIGEST_LIMIT="30"
    DEFAULT_ENFORCE_HISTORY="true"
    DEFAULT_HISTORY_MAX_FAIL="0"
    DEFAULT_HISTORY_MIN_PASS_RATE="1.0"
    ;;
  *)
    echo "error: HIVE_ACCEPTANCE_PROFILE must be one of: balanced, strict" >&2
    exit 1
    ;;
esac

SKIP_CHECKLIST="${HIVE_ACCEPTANCE_SKIP_CHECKLIST:-$DEFAULT_SKIP_CHECKLIST}"
SKIP_TELEGRAM="${HIVE_ACCEPTANCE_SKIP_TELEGRAM:-$DEFAULT_SKIP_TELEGRAM}"
REPORT_KEEP="${HIVE_ACCEPTANCE_REPORT_KEEP:-$DEFAULT_REPORT_KEEP}"
REPORT_PRUNE_APPLY="${HIVE_ACCEPTANCE_REPORT_PRUNE_APPLY:-$DEFAULT_REPORT_PRUNE_APPLY}"
DIGEST_DAYS="${HIVE_ACCEPTANCE_DIGEST_DAYS:-$DEFAULT_DIGEST_DAYS}"
DIGEST_LIMIT="${HIVE_ACCEPTANCE_DIGEST_LIMIT:-$DEFAULT_DIGEST_LIMIT}"
DIGEST_JSON_PATH="${HIVE_ACCEPTANCE_DIGEST_JSON_PATH:-docs/ops/acceptance-reports/digest-latest.json}"
DIGEST_MD_PATH="${HIVE_ACCEPTANCE_DIGEST_MD_PATH:-docs/ops/acceptance-reports/digest-latest.md}"
ENFORCE_HISTORY="${HIVE_ACCEPTANCE_ENFORCE_HISTORY:-$DEFAULT_ENFORCE_HISTORY}"
HISTORY_MAX_FAIL="${HIVE_ACCEPTANCE_HISTORY_MAX_FAIL:-$DEFAULT_HISTORY_MAX_FAIL}"
HISTORY_MIN_PASS_RATE="${HIVE_ACCEPTANCE_HISTORY_MIN_PASS_RATE:-$DEFAULT_HISTORY_MIN_PASS_RATE}"

hive_cron_require_crontab
hive_cron_validate_expr "$CRON_EXPR"
mkdir -p "$LOG_DIR"

CMD="HIVE_ACCEPTANCE_PROFILE=$(hive_cron_q "$PROFILE") \
HIVE_ACCEPTANCE_SKIP_CHECKLIST=$(hive_cron_q "$SKIP_CHECKLIST") \
HIVE_ACCEPTANCE_SKIP_TELEGRAM=$(hive_cron_q "$SKIP_TELEGRAM") \
HIVE_ACCEPTANCE_REPORT_KEEP=$(hive_cron_q "$REPORT_KEEP") \
HIVE_ACCEPTANCE_REPORT_PRUNE_APPLY=$(hive_cron_q "$REPORT_PRUNE_APPLY") \
HIVE_ACCEPTANCE_DIGEST_DAYS=$(hive_cron_q "$DIGEST_DAYS") \
HIVE_ACCEPTANCE_DIGEST_LIMIT=$(hive_cron_q "$DIGEST_LIMIT") \
HIVE_ACCEPTANCE_DIGEST_JSON_PATH=$(hive_cron_q "$DIGEST_JSON_PATH") \
HIVE_ACCEPTANCE_DIGEST_MD_PATH=$(hive_cron_q "$DIGEST_MD_PATH") \
HIVE_ACCEPTANCE_ENFORCE_HISTORY=$(hive_cron_q "$ENFORCE_HISTORY") \
HIVE_ACCEPTANCE_HISTORY_MAX_FAIL=$(hive_cron_q "$HISTORY_MAX_FAIL") \
HIVE_ACCEPTANCE_HISTORY_MIN_PASS_RATE=$(hive_cron_q "$HISTORY_MIN_PASS_RATE") \
/bin/bash $(hive_cron_q "$SCRIPT_PATH") >> $(hive_cron_q "$LOG_FILE") 2>&1"

hive_cron_upsert "$MARKER" "$CRON_EXPR" "$CMD"

echo "Installed $MARKER"
echo "cron: $CRON_EXPR"
echo "profile: $PROFILE"
echo "log: $LOG_FILE"
echo "script: $SCRIPT_PATH"

